# Generated by Django 5.1.2 on 2025-01-13 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('template_type', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
    ]
